filter:
    excluded_paths:
        - .scrutinizer.yml
build:
    nodes:
        analysis:
            resources:
                cpus: 1
            project_setup:
                override: true
            tests:
                override:
                    - php-scrutinizer-run --enable-security-analysis